import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Elearner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // TODO: Change `lang`
    <html lang="en" suppressHydrationWarning style={{ height: "100%" }}>
      <body style={{ height: "100%" }}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
